# render.yaml
services:
  - type: web
    name: excel-mcp-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn mcp_server:app --host 0.0.0.0 --port 10000"
    plan: free
